/**
 * Parse HECoS CSV data and generate synonym pairs for the search_synonyms table.
 *
 * HESA publishes two key files at https://www.hesa.ac.uk/innovation/hecos :
 *   1. HECoS vocabulary — preferred terms with HECoS codes
 *   2. Non-preferred terms — alternative names mapped to HECoS codes
 *
 * Download both CSVs manually (HESA blocks automated requests) and place them in:
 *   src/lib/data/hecos/hecos-vocabulary.csv
 *   src/lib/data/hecos/hecos-non-preferred.csv
 *
 * Usage: npx tsx scripts/build-synonyms.ts
 *
 * Output: Prints bidirectional [term, expandsTo] pairs in TypeScript format.
 * Append the output to the synonymPairs array in src/lib/data/search-synonyms.ts,
 * then re-run: npx tsx scripts/seed-synonyms.ts
 */

import { readFileSync, existsSync } from 'fs';
import { resolve } from 'path';

const DATA_DIR = resolve(import.meta.dirname, '../src/lib/data/hecos');
const VOCAB_FILE = resolve(DATA_DIR, 'hecos-vocabulary.csv');
const NON_PREFERRED_FILE = resolve(DATA_DIR, 'hecos-non-preferred.csv');

// Simple CSV line parser (handles quoted fields with commas)
function parseCsvLine(line: string): string[] {
	const fields: string[] = [];
	let current = '';
	let inQuotes = false;
	for (const char of line) {
		if (char === '"') {
			inQuotes = !inQuotes;
		} else if (char === ',' && !inQuotes) {
			fields.push(current.trim());
			current = '';
		} else {
			current += char;
		}
	}
	fields.push(current.trim());
	return fields;
}

function parseCsv(filePath: string): Record<string, string>[] {
	const content = readFileSync(filePath, 'utf-8');
	const lines = content.split('\n').filter((l) => l.trim());
	if (lines.length < 2) return [];

	const headers = parseCsvLine(lines[0]).map((h) => h.toLowerCase().replace(/\s+/g, '_'));
	return lines.slice(1).map((line) => {
		const values = parseCsvLine(line);
		const row: Record<string, string> = {};
		headers.forEach((h, i) => {
			row[h] = values[i] || '';
		});
		return row;
	});
}

// ─── Main ───────────────────────────────────────────────────────────────────

if (!existsSync(VOCAB_FILE)) {
	console.error(`Missing: ${VOCAB_FILE}`);
	console.error('Download the HECoS vocabulary CSV from https://www.hesa.ac.uk/innovation/hecos');
	process.exit(1);
}

if (!existsSync(NON_PREFERRED_FILE)) {
	console.error(`Missing: ${NON_PREFERRED_FILE}`);
	console.error(
		'Download the HECoS non-preferred terms CSV from https://www.hesa.ac.uk/innovation/hecos'
	);
	process.exit(1);
}

// Parse vocabulary: HECoS code → preferred term
const vocab = parseCsv(VOCAB_FILE);
const codeToPreferred = new Map<string, string>();
for (const row of vocab) {
	const code = row['hecos_code'] || row['code'] || row['id'] || '';
	const term = row['preferred_term'] || row['term'] || row['label'] || row['name'] || '';
	if (code && term) {
		codeToPreferred.set(code, term);
	}
}

// Parse non-preferred terms: HECoS code → non-preferred terms
const nonPreferred = parseCsv(NON_PREFERRED_FILE);
const codeToNonPreferred = new Map<string, string[]>();
for (const row of nonPreferred) {
	const code = row['hecos_code'] || row['code'] || row['id'] || '';
	const term =
		row['non-preferred_term'] || row['non_preferred_term'] || row['term'] || row['label'] || '';
	if (code && term) {
		if (!codeToNonPreferred.has(code)) {
			codeToNonPreferred.set(code, []);
		}
		codeToNonPreferred.get(code)!.push(term);
	}
}

// Build bidirectional pairs: preferred ↔ each non-preferred term
const pairs: [string, string][] = [];
for (const [code, preferred] of codeToPreferred) {
	const alts = codeToNonPreferred.get(code);
	if (!alts || alts.length === 0) continue;

	for (const alt of alts) {
		// Bidirectional: preferred ↔ non-preferred
		pairs.push([preferred.toLowerCase(), alt.toLowerCase()]);
		pairs.push([alt.toLowerCase(), preferred.toLowerCase()]);
	}
}

// Sort for readability
pairs.sort((a, b) => a[0].localeCompare(b[0]) || a[1].localeCompare(b[1]));

// Output as TypeScript pairs
console.log(`// Generated by scripts/build-synonyms.ts — do not edit manually`);
console.log(`// Source: HESA HECoS vocabulary (${codeToPreferred.size} codes)`);
console.log(`// Non-preferred terms mapped: ${codeToNonPreferred.size} codes`);
console.log(`// Synonym pairs generated: ${pairs.length}`);
console.log('');
console.log('// ─── HECoS-derived pairs (append to synonymPairs in search-synonyms.ts) ──');
for (const [term, expandsTo] of pairs) {
	console.log(`\t['${term.replace(/'/g, "\\'")}', '${expandsTo.replace(/'/g, "\\'")}'],`);
}
